In [2]:
#csv 파일을 불러들임. columns이름 있으니 따로 설정할 필요 없음
import pandas as pd
import numpy as np

df = pd.read_excel("C:/Users/Parkjunhan/Desktop/Raisin_Dataset/Raisin_Dataset/Raisin_Dataset.xlsx")
df

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0    87524       442.246011       253.291155      0.819738       90546   
1    75166       406.690687       243.032436      0.801805       78789   
2    90856       442.267048       266.328318      0.798354       93717   
3    45928       286.540559       208.760042      0.684989       47336   
4    79408       352.190770       290.827533      0.564011       81463   
..     ...              ...              ...           ...         ...   
895  83248       430.077308       247.838695      0.817263       85839   
896  87350       440.735698       259.293149      0.808629       90899   
897  99657       431.706981       298.837323      0.721684      106264   
898  93523       476.344094       254.176054      0.845739       97653   
899  85609       512.081774       215.271976      0.907345       89197   

       Extent  Perimeter    Class  
0    0.758651   1184.040  Kecimen  
1    0.684130   1121.786  Kecimen  
2    0.637613   1208.575  Kecimen  
3    0.699599    844.162  Kecimen  
4    0.792772   1073.251  Kecimen  
..        ...        ...      ...  
895  0.668793   1129.072    Besni  
896  0.636476   1214.252    Besni  
897  0.741099   1292.828    Besni  
898  0.658798   1258.548    Besni  
899  0.632020   1272.862    Besni  

[900 rows x 8 columns]

In [3]:
# x,y 나누는 코드 

X=df.drop('Class',axis=1) #axis=0or1임. 1로하면 x축을 기준으로 나눔. 0은 y축을 기준으로 나눔. 
X.head()

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0  87524       442.246011       253.291155      0.819738       90546   
1  75166       406.690687       243.032436      0.801805       78789   
2  90856       442.267048       266.328318      0.798354       93717   
3  45928       286.540559       208.760042      0.684989       47336   
4  79408       352.190770       290.827533      0.564011       81463   

     Extent  Perimeter  
0  0.758651   1184.040  
1  0.684130   1121.786  
2  0.637613   1208.575  
3  0.699599    844.162  
4  0.792772   1073.251

In [4]:
# x,y 나누는 코드 

y=df['Class']
y.value_counts()

Kecimen    450
Besni      450
Name: Class, dtype: int64

In [5]:
# x트레인,y트레인,x테스트,y테스트로 코드 나눠줌

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [6]:
# 라이브러리 import 

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [7]:
# X_train, y_train으로 훈련 (밑에서부터 5개의 다른 모델을 적용해서 ML, 최소 Logisregression은 하기)

from sklearn.svm import SVC

clf_svm = SVC(random_state=0)    # SVM 모델
clf_svm.fit(X_train, y_train)    # fit 함수로 훈련

pred_svm = clf_svm.predict(X_test)  # 테스트값으로 훈련 잘했나 비교하기 위해 예측값 생성

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))     #예측값과 비교하는 코드(y테스트와 pred_svm과 비교)
print(confusion_matrix(y_test, pred_svm))   #혼동행렬 출력


--- SVM Classifier ---
0.8133333333333334
[[ 83  32]
 [ 10 100]]


In [8]:
clf_lr = LogisticRegression(random_state=0)  #LogisticRegrssion 모델     *변수이름 바꿔보기
clf_lr.fit(X_train, y_train)  # fit 함수로 훈련

pred_lr = clf_lr.predict(X_test)  

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.8844444444444445
[[ 99  16]
 [ 10 100]]


In [9]:
clf_dt = DecisionTreeClassifier(random_state=0) #모델 결정
clf_dt.fit(X_train, y_train) #fit시킴

pred_dt = clf_dt.predict(X_test) #평가

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.7911111111111111
[[91 24]
 [23 87]]


In [10]:
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.52
[[ 11 104]
 [  4 106]]


In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.8622222222222222
[[97 18]
 [13 97]]
